### ISSUE TITLE
reproduce procedure

### ISSUE THREAD

**Issue by wahr0411** [zhouhanxie/PRAG#1]
Hi there, I really appreciate your work. 

Could you offer scripts to reproduce the whole experiment? In what order should I make use of the source code?

You've mentioned that "Guided generator is the inference directory, with dependency on trained personalized retriever and embedding estimator." Is it right to train the personalized retriever and embedding estimator repectively, and then run train_generator.py under /guided_generator/?

**Comment by zhouhanxie** [comment]
Hi there, thanks for your interest!

Unfortunately I don't have the original scripts anymore  (this repo is from the anonymized pack - the bash scripts contains various server names, user names back then)

The important hyper-parameters are in the appendix (for the rest you can use the default ones + HF default, PRAG shouldn't be too sensitive to hyper-parameters)

The order of training is 

- personalied_retriever/train_retriever.py （```data_path``` and ```index_dir``` arguments are from [previous works](https://github.com/lileipisces/NLG4RS))
  - At this point you can produce embeddings to retrieve reviews + predict ratings
  - For how to do retrieval see ```prag_generation/generate_review.py```
 - Then you can use any generation module to aggregate the retrieved reviews.
   - We used unifiedQA (fine-tuned on a couple of hand written samples to aggregate retrieved reviews in ```train_generator.py```), but now w/ LLMs I _think_ you can also prompt a model to summarize the reviews and obtain good diversity + factuality, etc.
 - The embedding interpreter is optional (embedding_interpreter/train_interpreter.py) if you did end up using other generation module. In case you need it, the script arguments are automatically determined base on dataset. 
 - If you have all the 3 components, you should be able to run ```[generate_review.py](https://github.com/zhouhanxie/PRAG/blob/main/prag_generation/generate_review.py)```. (It contains the code to load all trained components and use them to produce reviews)

**Comment by zhouhanxie** [comment]
Closing the issue for now, but feel free to ping me if you need anything.

**Comment by 3256942614** [comment]
Hi there, I really appreciate your work
I need cached when running_ Review_ Embedding='transformer_ Retriever/Yelp_ I think there needs to be a transformer for the data of table.npy_ Retrieve. py to generate data, but I couldn't find it in the code. May I ask if a transformer is needed_ Retrieve. py is still available in the downloaded dataset？

**Comment by zhouhanxie** [comment]
> Hi there, I really appreciate your work I need cached when running_ Review_ Embedding='transformer_ Retriever/Yelp_ I think there needs to be a transformer for the data of table.npy_ Retrieve. py to generate data, but I couldn't find it in the code. May I ask if a transformer is needed_ Retrieve. py is still available in the downloaded dataset？

Hi, I'm not sure I fully grasp the question yet but for my code all the cache should be optional - if you remove those links it will generate one for you (you can trace it via functions calls etc. to see the mechanism if that's helpful). Hope this helps!
